import { defineConfig } from 'orval';

/**
 * Orval 配置文件
 *
 * 用于从 OpenAPI 文档生成 TypeScript API 客户端代码
 */
export default defineConfig({
  api: {
    // 输入：OpenAPI 文档
    input: {
      target: 'http://localhost:3001/openapi.json',
      // 使用 transformer 根据 API 路径自动生成英文 tag
      override: {
        transformer: './scripts/api/transform-openapi.ts',
      },
    },

    // 输出配置
    output: {
      // 输出目录和文件
      target: './src/api/generated/index.ts',

      // 客户端类型：使用 axios 函数
      client: 'axios-functions',

      // 输出模式：按 tags 分割（tags 由 transformer 根据路径生成）
      mode: 'tags-split',

      // Schemas 配置：分离 schemas 文件，避免与主文件混在一起
      schemas: './src/api/generated/model',

      // 覆盖配置
      override: {
        // 使用自定义 mutator（连接到现有的 HttpClient）
        mutator: {
          path: './src/api/core/mutator.ts',
          name: 'customMutator',
        },

        // 自定义导入语句
        header: () => [
          '/**',
          ' * Generated by Orval',
          ' * Do not edit manually.',
          ' * ',
          ' * 此文件由 Orval 自动生成，请勿手动修改',
          ' * 如需自定义接口，请在 src/api/custom/ 目录下创建覆盖文件',
          ' */',
        ],
      },
    },

    // 钩子：生成后自动格式化并更新导出
    hooks: {
      afterAllFilesWrite: [
        'eslint --fix',
        'prettier --write',
        'npx tsx scripts/api/update-api-exports.ts',
      ],
    },
  },
});
