/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/cart/cart" |
  "/pages/category/category" |
  "/pages/login/index" |
  "/pages/mine/mine" |
  "/pages/register/index" |
  "/pages-sub/order/create-order" |
  "/pages-sub/order/order-detail" |
  "/pages-sub/order/order" |
  "/pages-sub/order/pay-success" |
  "/pages-sub/order/pay" |
  "/pages-sub/user/brand-attention" |
  "/pages-sub/user/product-collection" |
  "/pages-sub/user/read-history" |
  "/pages-sub/user/set" |
  "/pages-sub/user/user-info" |
  "/pages-sub/product/hot-product-list" |
  "/pages-sub/product/list" |
  "/pages-sub/product/new-product-list" |
  "/pages-sub/product/product";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url:
    | '/pages/index/index'
    | '/pages/category/category'
    | '/pages/cart/cart'
    | '/pages/mine/mine';
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module 'virtual:uni-pages' {
  export type LocationUrl = _LocationUrl;
}
