/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

type _LocationUrl =
  "/pages/index/index" |
  "/pages/address/address" |
  "/pages/address/addressManage" |
  "/pages/brand/brandDetail" |
  "/pages/brand/list" |
  "/pages/cart/cart" |
  "/pages/category/category" |
  "/pages/coupon/couponList" |
  "/pages/money/money" |
  "/pages/money/pay" |
  "/pages/money/paySuccess" |
  "/pages/notice/notice" |
  "/pages/product/list" |
  "/pages/product/product" |
  "/pages/public/login" |
  "/pages/public/register" |
  "/pages/user/user" |
  "/pages-sub/order/createOrder" |
  "/pages-sub/order/order" |
  "/pages-sub/order/orderDetail" |
  "/pages-sub/user/brandAttention" |
  "/pages-sub/user/productCollection" |
  "/pages-sub/user/readHistory" |
  "/pages-sub/user/set" |
  "/pages-sub/user/userinfo" |
  "/pages-sub/product/hotProductList" |
  "/pages-sub/product/newProductList";

interface NavigateToOptions {
  url: _LocationUrl;
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url:
    | '/pages/index/index'
    | '/pages/category/category'
    | '/pages/cart/cart'
    | '/pages/user/user';
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}

declare module 'virtual:uni-pages' {
  export type LocationUrl = _LocationUrl;
}
